server:
  port: ${SERVER_PORT:9091}
security:
  basic:
    enabled: true
  user:
    name: ${DISCOVERY_USER:user}
    password: ${DISCOVERY_PASS:password}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
        defaultZone: ${SVC_DISCOVERY:http://user:password@localhost:9091/eureka/}